
teleop:
  filename: js.yaml
  plugin: gen3_lite
  plugin_args:
    constraints:
      - x: [-0.1, 0.1]
      - y: [-0.1, 0.1]
      - z: [0, 0.3]
      - buffer_multiplier: 2
plugin: gen3_lite
plugin_args:
  constraints:
    - x: [-0.1, 0.1]
    - y: [-0.1, 0.1]
    - z: [0, 0.3]
    - buffer_multiplier: 2
# axes:
#   - deadzone: 0.0
#     output: AXIS_Y
#     scale: 1.0
#   - deadzone: 0.0
#     output: AXIS_X
#     scale: 1.0
#   - deadzone: 0.0
#     output: null
#     scale: 1.0
#   - deadzone: 0.05
#     output: AXIS_PITCH
#     scale: -1.0
#   - deadzone: 0.1
#     output: AXIS_ROLL
#     scale: -1.0
#   - deadzone: 0.1
#     output: null
#     scale: 1.0
#   - deadzone: 0.0
#     output: AXIS_YAW
#     scale: 2.0
#   - deadzone: 0.0
#     output: AXIS_Z
#     scale: 1.0
axes:
  - deadzone: 0.0
    output: AXIS_Y
    scale: 0.5
  - deadzone: 0.0
    output: AXIS_X
    scale: 0.5
  - deadzone: 0.0
    output: null
    scale: 1.0
  - deadzone: 0.05
    output: AXIS_PITCH
    scale: 1.0
  - deadzone: 0.1
    output: AXIS_Z
    scale: 0.4
  - deadzone: 0.1
    output: null
    scale: 1.0
  - deadzone: 0.0
    output: null
    scale: 2.0
  - deadzone: 0.0
    output: null
    scale: 1.0
buttons:
  - output: null
  - output: null
  - output: null
  - output: null
  - output: OPEN_GRIPPER
  - output: CLOSE_GRIPPER
  - output: OPEN_GRIPPER
  - output: CLOSE_GRIPPER
  - output: GO_HOME_COMMAND
  - output: null
  - output: null
logging:
  added_loggers:
  - rosbag
  auto: true
  rosbag:
    enabled: true
    topics:
    - /camera_obs__dev_video0_96x96
    - /camera_obs__dev_video1_96x96
    - /camera_obs__dev_video2_96x96
    - /camera_obs__dev_video3_96x96
    - /camera_obs__dev_video4_96x96
    - /camera_obs__dev_video5_96x96
    - /joy
    - /my_gen3_lite/in/cartesian_velocity
    - /my_gen3_lite/base_feedback
    - /my_gen3_lite/base_feedback/joint_state
    - /my_gen3_lite/joint_states
    - /reward
    - /success
    - /tf