axes:
  - deadzone: 0.0           #1
    output: AXIS_X # Left joystick horizontal - rotation around X-axis
    scale: 1.0
  - deadzone: 0.0        #2
    output:  AXIS_Y # Left joystick vertical - rotation around Y-axis
    scale: 1.0
  - deadzone: 0.0       #3
    output:  AXIS_Z # left button front
    scale: 1.0
  - deadzone: 0.05      #4
    output:  AXIS_PITCH # Right joystick horizontal - linear movement along X-axis
    scale: -1.0
  - deadzone: 0.1    #5
    output:  AXIS_ROLL # Right joystick vertical - linear movement along Y-axis
    scale: -1.0
  - deadzone: 0.1   #6
    output: # Right button front
    scale: 1.0
  - deadzone: 0.0 # direction button horizontal 
    output: AXIS_YAW # Unused axis
    scale: 2.0
  - deadzone: 0.0 # direction button vertical 
    output:  "AXIS_Z"   # Unused axis
    scale: 1.0
buttons:
  - output: OPEN_GRIPPER # The following four is one of the x y a b
  - output: CLOSE_GRIPPER # 
  - output: GO_HOME_COMMAND  # Unused button
  - output:   # Unused button
  - output: # Unused button
  - output: # Unused button
  - output: ''  # Unused button
  - output: ''  # Unused button
  - output:  #  XBox button
  - output: ''  # Unused button
  - output: ''  # Unused button
logging:
  added_loggers:
  - rosbag
  auto: true
  rosbag:
    enabled: true
    topics:
    - /cam_dev_video0
    - /cam_dev_video1
    - /cam_dev_video2
    - /cam_dev_video3
    - /cam_dev_video4
    - /cam_dev_video5
    - /joy
    - /my_gen3_lite/in/cartesian_velocity
    - /my_gen3_lite/base_feedback
    - /my_gen3_lite/base_feedback/joint_state
    - /my_gen3_lite/joint_states
    - /reward
    - /success